server:
  port: 8000
  servlet:
    context-path: /kbp
spring:
  datasource:
    username: kbpdata
    url: jdbc:oracle:thin:@120.52.78.23:1526:kbp
    password: kbpdata
    driver-class-name: oracle.jdbc.OracleDriver


